### ISSUE TITLE
Create github action that will build the c++ code on supported operating systems

### ISSUE THREAD

**Issue by drewoldag** [lephare-photoz/lephare#15]
We've been chasing around which operating systems the c code will compile on. We should implement a quick github action to ensure that the c++ code compiles on supported operating system.

FWIW we could start with something like this: 
```
name: C++ CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        gcc_version: [7, 8, 9]
        exclude:
          - os: macos-latest
            gcc_version: 7
          - os: macos-latest
            gcc_version: 8

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-${{ matrix.gcc_version }}

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install gcc@9

    - name: Build
      run: |
        cd ./src/lib
        make
```
